#:schema node_modules/wrangler/config-schema.json
name = "cloudflare-workers-prisma-connection"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat_v2"]
main = "./src/index.ts"

[observability]
enabled = true
